project:
  type: website
  output-dir: docs

publish:
  method: gh-pages

website:
  title: "Johanna-Marie Kreher"
  navbar:
    search: true
    left:
      - text: "About"
        file: index.qmd
      - file: psd.qmd
      - file: vision.qmd
      - file: zukunft.qmd
      - file: miteinander.qmd
# sidebar:
#     collapse-level: 1
#     style: "floating"
#     contents:
#       - text: "About"
#         file: index.qmd
#       - text: "Aktuell"
#         file: psd.qmd
#       - file: vision.qmd
#       - file: zukunft.qmd
#       - file: miteinander.qmd
format:
  html:
    theme: cosmo # themes: https://quarto.org/docs/output-formats/html-themes.html
    css: styles.css
    toc: true



